FROM node:14

# Installing libvips-dev for sharp compatability
# RUN apt-get update && apt-get install libvips-dev

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

WORKDIR /srv/app

VOLUME /srv/app

COPY ./yarn.lock ./
COPY ./@app/strapi/ ./

RUN yarn install

EXPOSE 1337

CMD ["yarn", "develop"]
